### ISSUE TITLE
Having a ColorRect as a sibling of the Pawn stops all the mouse input, disabling the camera and clicks

### ISSUE THREAD

**Issue by pkostic-dev** [ratmarrow/GoldGdt#1]
I have a ColorRect that is on full screen since it has an overlay shader applied to it. This makes the mouse input stop. It causes the camera and the clicks to stop functioning for the Pawn. This is because the mouse events are handled in the `_unhandled_input(event)` in the source code and mouse input will directly interact with the fullscreen ColorRect node and therefore the events are consumed. The ColorRect nodes are by default set to `filter_mouse = MOUSE_FILTER_STOP`.

Steps to recreate :
- Add the Pawn scene as a child to a Node3D.
- Add a ColorRect as a child to the same node, before or after the Pawn, it doesn't matter.

Presumably any Control node that can take up the whole screen and stops mouse input by default may cause the same issue.

Two proposed solutions :
- In the source code : handle the mouse input in `_input(event)`
- Externally : change the mouse_filter property of all such Control nodes to Pass or Ignore (user side)

**Comment by ratmarrow** [comment]
Yeah, I had noticed as such when developing, I will just change it to use `_input(event)` because it seems to incur no weird effects.
