### ISSUE TITLE
Suggestion for unduck behaviour

### ISSUE THREAD

**Issue by kareigu** [ratmarrow/GoldGdt#2]
Hi,
Firstly it's great to see more people trying to tackle porting these movement mechanics to Godot.

I noticed you're using an array of Ray3Ds to handle unduck ceiling detection. 
I used this approach in my version of this movement system at first as well and found it a bit too hacky and not completely reliable, so I did some more research to see if it could be handled in the same way Quake/GoldSrc handle their collisions.

Eventually I found this [great article](https://thelowrooms.com/articledir/programming_stepclimbing.php) on handling stairs (which I figure will help you out as well in the future), which lead me to [PhysicsDirectSpaceState3D](https://docs.godotengine.org/en/stable/classes/class_physicsdirectspacestate3d.html#class-physicsdirectspacestate3d-method-collide-shape) and specifically its method `collide_shape`. 
With this you could just use your standing hull to check for ceiling collisions. 
Been using this for some time now in my own implementation and it works really well with no need to spam a bunch of rays out.

Hope this helps and looking forward to how you progress.

**Comment by ratmarrow** [comment]
Wrapping up schoolwork, but will definitely give this a read and work on an update!

**Comment by ratmarrow** [comment]
Crouching now works identically to GoldSrc as of Update 2.
