### ISSUE TITLE
Missing dependencies: CS.tres

### ISSUE THREAD

**Issue by xSnipah** [ratmarrow/GoldGdt#2]
![image](https://github.com/ratmarrow/GoldGdt/assets/160337060/06a86ef1-875b-4b46-975b-629bfa3cb886)
Created a new project, imported the addon, enabled the plugin then restarted godot.

**Comment by xSnipah** [comment]
Renaming "Default.tres" to "CS.tres" fixed the issue.

**Comment by ratmarrow** [comment]
huh, weird. i created that outside of the add-on locally for something, i thought i had removed all links to it but i guess not

will find a solution because that should NOT be happening

**Comment by ratmarrow** [comment]
update, i cannot seem to replicate the issue at all, the current version doesn't seem to have this issue at all

you should be able to do a fresh install the add-on and the problem _shouldn't_ be there.
